version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80" # Expose le port 8010 pour l'application
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: boris
      DB_PASS: Mpdiliee27
      DB_NAME: todolist_base
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gfm2nlape
      MYSQL_DATABASE: todolist_base
      MYSQL_USER: boris
      MYSQL_PASSWORD: Mpdiliee27
    ports:
      - "3310:3306" # Expose le port 3310 pour MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: